name: NPM Publish
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Dependencies
        run: npm ci

      - name: Install Peer Dependencies
        run: npm i vue@3.1.2 @microsoft/signalr@5.0.7 --no-save

      - name: Build Package
        run: npm run build

      - name: Run Tests
        run: npm test -- --single-run --browsers ChromeHeadlessCI

      - name: Run Linting
        run: npm run lint

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
